import Head from "next/head";
import { MainNav } from "~/components/main-nav";
import TeamSwitcher from "~/components/team-switcher";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { UserNav } from "~/components/user-nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Horario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <TeamSwitcher />
              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                <UserNav />
              </div>
            </div>
          </div>
          <div className="flex-1 space-y-4 p-8 pt-6">
            <div className="flex items-center justify-between space-y-2">
              <h2 className="text-3xl font-bold tracking-tight">Schedule</h2>
            </div>
            <Tabs defaultValue="overview" className="space-y-4">
              <TabsList>
                <TabsTrigger value="schedule">Overview</TabsTrigger>
                <TabsTrigger value="calendar" disabled>
                  Calendar
                </TabsTrigger>
              </TabsList>
              <TabsContent value="schedule" className="space-y-4"></TabsContent>
            </Tabs>
          </div>
        </div>
      </main>
    </>
  );
}
